CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notas (
  id SERIAL PRIMARY KEY,
  texto TEXT NOT NULL,
  fecha TIMESTAMP DEFAULT NOW(),
  fecha_asignada DATE,
  user_id INTEGER REFERENCES usuarios(id)
);
