name: CI - MiniNotas

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: mininotas
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U devuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: 📥 Checkout repo
      uses: actions/checkout@v3

    - name: 🟢 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 📦 Instalar dependencias del backend
      working-directory: ./backend
      run: npm install

    - name: 🧪 Test del backend
      working-directory: ./backend
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: devuser
        DB_PASSWORD: devpass
        DB_NAME: mininotas
        NODE_ENV: test
      run: |
        sleep 5
        npm test

    - name: 📦 Instalar dependencias del frontend
      working-directory: ./frontend
      run: npm install

    - name: 🧪 Test del frontend
      working-directory: ./frontend
      run: npm test
